---
version: '3.8'

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
    - --path.rootfs=/host
    - --no-collector.rapl
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
    - '/:/host:ro,rslave,Z'
  dcgm_exporter:
    image: nvcr.io/nvidia/k8s/dcgm-exporter:2.4.5-2.6.7-ubuntu20.04
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    user: root
    cap_add:
    - SYS_ADMIN
    ports:
    - 9400:9400
    environment:
    - DCGM_EXPORTER_LISTEN=:9400
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    restart: unless-stopped
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
    - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    - ./data:/prometheus/data:Z
    depends_on:
    - node_exporter
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    ports:
    - 3000:3000
    user: root
    volumes:
    - ./grafana:/var/lib/grafana:Z
    - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
    - ./dashboard-definition.yaml:/etc/grafana/provisioning/dashboards/dashboard-definition.yaml:ro
    - ./node-exporter.json:/tmp/node-exporter.json
    - ./dcgm-exporter.json:/tmp/dcgm-exporter.json
